### ISSUE TITLE
目录很乱

### ISSUE THREAD

**Issue by BBleae** [BBleae/hrt-book#1]
![image](https://user-images.githubusercontent.com/13044102/165979910-799a8cad-fd85-44c9-88d0-0d73da6ae640.png)
比如这种情况，层次关系混乱

**Comment by KiritaniAyaka** [comment]
Part8 比较特殊，有两级标题，迷迷糊糊按前几个 Part 的习惯为每一个原 slide 里的页面建了二级标题…

另外是否有必要把部分标题里的说明性文字（括号里和破折号后）删除或者移动到正文里呢

**Comment by BBleae** [comment]
目录里还是不要用破折号
尽量用层级关系
