### ISSUE TITLE
使侧边栏可以跨目录导航

### ISSUE THREAD

**Issue by LiAlH4qwq** [BBleae/hrt-book#19]
现在通过目录点开某一章节后，在侧边栏无法导航到其他章节，而必须返回目录，是否应该优化这一行为，使侧边栏可以跨目录导航，类似mtfwiki

**Comment by KiritaniAyaka** [comment]
在不引入新的插件和主题的情况下，VuePress 自动生成的侧边栏不能展开非当前文档中的二级标题，目前只能将其他章节的链接放在侧边栏中。

![1](https://github.com/BBleae/hrt-book/assets/26200808/0e9f16b0-4f8d-434d-9163-d4dffc32df9b)

这种实现方式点击标题会跳转，无法在不跳转的情况下展开

---

![2](https://github.com/BBleae/hrt-book/assets/26200808/16d165e5-0618-40a4-a858-183aacf70556)

这种方式无法索引二级标题，但有自行解析 md 文档并添加二级标题的可行性

**Comment by KiritaniAyaka** [comment]
通过插件实现了
