### ISSUE TITLE
如果我要部署一个镜像，我应该怎么做？

### ISSUE THREAD

**Issue by ThEWiZaRd0fBsoD** [BBleae/hrt-book#20]
我有一个国内备案域名，但那个域名空闲着所以我想利用起来。
请问，我应该怎么做？
（有一台运行着Nginx的服务器）。

**Comment by BBleae** [comment]
用 `pnpm build` 来构建，然后把构建出来的文件放到 wwwroot  即可
你可以写个脚本实现自动拉取并构建

**Comment by ThEWiZaRd0fBsoD** [comment]
> 用 `pnpm build` 来构建，然后把构建出来的文件放到 wwwroot 即可 你可以写个脚本实现自动拉取并构建

好👌
