### ISSUE TITLE
Are You MrEdd?

### ISSUE THREAD

**Issue by XxMrGod0703xX** [BBleae/hrt-book#21]
hello eugennnnnnn
are u mredd?(XxMrEdd0703xX)

**Comment by BBleae** [comment]
What are you talking about?

**Comment by XxMrGod0703xX** [comment]
> 你在谈论什么？

It's fine, I just wanted to ask https://github.com/EuGennnnnnn if this person is someone I knew before

**Comment by BBleae** [comment]
I don't know that person.

**Comment by XxMrGod0703xX** [comment]
> 我不认识那个人。

ok,ty
