### ISSUE TITLE
是否应该在相关链接中加入MTF Wiki

### ISSUE THREAD

**Issue by LiAlH4qwq** [BBleae/hrt-book#8]
Rt，是否应该将希望查询HRT之外内容的用户导流到MTF Wiki

**Comment by LiAlH4qwq** [comment]
wiki方面似乎因为“替代医学”等原因，暂不计划添加backlink，但跟据咱的观察，在transf相关网站中，单向友链的现象并不少见(毕竟目的是帮助尽可能多的姐妹吧

**Comment by BBleae** [comment]
嗯，有考虑添加友链
